function skillsMember() {
    // Skills
    var skills = new Array();
    skills.push("HTML");
    skills.push("CSS");
    skills.push("JavaScript");
    skills.push("PHP");
    skills.push("MySQL");
    skills.push("Python");
    skills.push("Java");
    skills.push("C++");
    skills.push("C#");
    skills.push("Ruby");
    skills.push("Swift");
    skills.push("Objective-C");
    skills.push("R");
    skills.push("Perl");
    skills.push("Scala");
    skills.push("Go");
    skills.push("Shell");
    skills.push("SQL");
    skills.push("Haskell");
    skills.push("Lua");
    skills.push("Clojure");
    skills.push("Erlang");
    skills.push("Kotlin");
    skills.push("TypeScript");
    skills.push("CoffeeScript");
    skills.push("Dart");
    skills.push("F#");
    skills.push("Rust");
    skills.push("Groovy");
    skills.push("Visual Basic");
    skills.push("Pascal");
    skills.push("Lisp");
    skills.push("Assembly");
    skills.push("Fortran");
    skills.push("Ada");
    skills.push("Scheme");
    skills.push("Prolog");
    skills.push("Smalltalk");
    skills.push("Ocaml");
    skills.push("Racket");
    skills.push("Cobol");
    skills.push("D");
    skills.push("ActionScript");
    skills.push("ABAP");
    skills.push("Apex");
    skills.push("AutoLISP");
    skills.push("Awk");
    skills.push("Bash");
    skills.push("BASIC");
    skills.push("Batch");
    skills.push("C");
    skills.push("Caml");
    skills.push("CFML");
    skills.push("Clipper");
    skills.push("COBOL");
    skills.push("ColdFusion");
    skills.push("Common Lisp");
    skills.push("Crystal");
    skills.push("DCL");
    skills.push("Delphi");
    skills.push("Eiffel");
    skills.push("Elixir");
    skills.push("Emacs Lisp");
    skills.push("EmberScript");
    skills.push("Euphoria");
    skills.push("Forth");
    skills.push("FoxPro");
    skills.push("Game Maker Language");
    skills.push("GML");
    skills.push("Harbour");
    skills.push("HTML5");
    skills.push("Icon");
    skills.push("IDL");
    skills.push("Inform");
}